version: '3'
services:
  orderdrinks-vuejs:
    build: .
    container_name: orderdrinks-vuejs
    ports:
      - "5050:5050"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
    networks:
      - My-Orderdrinks

networks:
  My-Orderdrinks:
    name: My-Orderdrinks
