version: '3'
services:
  orderdrinks-vuejs:
    image: orderdrinks-vuejs:latest
    container_name: orderdrinks-vuejs
    ports:
      - "5050:5050"
    environment:
      - NODE_ENV=production
    volumes:
      - ./env:/app/.env
    networks:
      - My-Orderdrinks

networks:
  My-Orderdrinks:
    name: My-Orderdrinks

volumes:
  env:
