version: '3'
services:
  orderdrinks-vuejs:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: orderdrinks-vuejs
    container_name: orderdrinks-vuejs
    ports:
      - "5050:5050"
    environment:
      - NODE_ENV=production
      - VITE_LONGDO_MAP_API_KEY=${VITE_LONGDO_MAP_API_KEY}
      - VITE_API_URL=${VITE_API_URL}
      - VITE_WEBSOCKET_URL=${VITE_WEBSOCKET_URL}
    env_file:
      - .env
    volumes:
      - ./.env:/app/.env
    networks:
      - My-Orderdrinks

networks:
  My-Orderdrinks:
    name: My-Orderdrinks
    driver: bridge
    external: true

volumes:
  env:
