version: '3'
services:
  orderdrinks-vuejs:
    build: .
    container_name: orderdrinks-vuejs
    ports:
      - "80:3000"
    volumes:
      - .:/app/vue
      - /app/vue/node_modules
    environment:
      - NODE_ENV=production
    networks:
      - My-Orderdrinks

networks:
  My-Orderdrinks:
    name: My-Orderdrinks