name: Build and Push Docker Image

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t orderdrinks-vuejs:${{ github.sha }} .

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.VM_SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.VM_KNOWN_HOSTS }}

      - name: Push to VM and Run
        env:
          HOST: ${{ secrets.VM_HOST }}
          USER: ${{ secrets.VM_USER }}
        run: |
          docker save orderdrinks-vuejs:${{ github.sha }} | ssh $USER@$HOST 'docker load'
          ssh $USER@$HOST 'docker-compose -f ~/docker-compose.yml up -d orderdrinks-vuejs'
