name: Build and Deploy to Azure VM

on:
  push:
    branches:
      - main
      - develop
      - develop-test

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/orderdrinks-vuejs:${{ github.ref_name }}-${{ github.sha }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/develop-test'
    steps:
      - name: Execute remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: ${{ secrets.AZURE_VM_USERNAME }}
          key: ${{ secrets.AZURE_VM_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd ~/orderdrinks-vuejs-${{ github.ref_name }}
            echo ${{ github.ref_name }}-${{ github.sha }} > version.txt
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/orderdrinks-vuejs:${{ github.ref_name }}-${{ github.sha }}
            docker-compose down
            sed -i 's|image: .*|image: ${{ secrets.DOCKERHUB_USERNAME }}/orderdrinks-vuejs:${{ github.ref_name }}-${{ github.sha }}|' docker-compose.yml
            docker-compose up -d